name: change_first_order

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"] #["3.8", "3.9", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Start external services
      run: docker compose up -d
    - name: Install the project and its dependencies
      run: pip install -e .[test]
    - name: Install pytest-ranking
      run: pip install pytest-ranking
    - name: Restore pytest-ranking cache
      id: restore-pytest-ranking-cache
      if: always()
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranking_data
        key: pytest-ranking-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.python }}
    - name: Test with pytest
      run: coverage run -m pytest -v --durations=0 --rank --rank-weight=0-0-1
    - name: Save pytest-ranking cache
      id: save-pytest-ranking-cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/.pytest_cache/v/pytest_ranking_data
        key: pytest-ranking-cache-${{ github.workflow }}-${{ runner.os }}-${{ matrix.python }}-${{ github.run_id }}
